version: "3"

tasks:
  default:
    desc: "Run default task"
    cmds:
      - task: "install"
      - task: "format"
      - task: "lint"
      - task: "build"

  install:
    desc: "Install dependencies"
    sources:
      - package.json
      - package-lock.json
    cmds:
      - pnpm i

  format:
    desc: "Format code"
    deps:
      - install
    cmds:
      - pnpm run format

  lint:
    desc: "Lint code"
    deps:
      - install
    cmds:
      - pnpm run lint

  lint:fix:
    desc: "Lint code and fix issues"
    deps:
      - install
    cmds:
      - pnpm run lint:fix

  build:
    desc: "Build project"
    deps:
      - install
    cmds:
      - pnpm run build

  deploy:
    desc: "Deploy project"
    deps: 
      - build
    cmds:
      - >-
        rclone sync dist/ :ftp:/ \
          --ftp-host=${FTP_HOST} \
          --ftp-user=${FTP_USER} \
          --ftp-pass=$(rclone obscure ${FTP_PASSWORD}) \
          --ftp-explicit-tls=true
    requires:
      vars:
        - FTP_HOST
        - FTP_USER
        - FTP_PASSWORD

  clean:
    desc: "Clean build artifacts"
    cmds:
      - rm -rf dist

  dev:
    desc: "Run development server"
    deps:
      - install
    cmds:
      - pnpm run dev
